Add files via upload
MichaelaRadimska/Acceptance-tests-php pull request #1
Opened 2018-05-10 14:39 UTC by MichaelaRadimska

Seznam Homepage Acceptance Test
TODO (to learn how to test):
- javascript (ev)
- listbox (https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/listbox/listbox-scrollable.html) - logout, select login domain, select language (dictionary)
- currentUrl (current URL = default adress ('/'), not the new one? Possible solution? - I haven´t read yet: https://stackoverflow.com/questions/38855330/get-the-full-request-url-from-webdriver-module-in-codeception/38855743#38855743)
- cookies
- new window

2018-05-10 20:19 UTC, martinvenus commented on AcceptanceTester.php
> +    public function verifyLink($link,$text){
Bylo by dobré používat striktní typování. Podobně jako v Javě nebo C#. U každého parametru tedy mít i datový typ. Zároveň uvést na začátku souboru declare(strict_types = 1);

2018-05-10 20:24 UTC, martinvenus requested changes

2018-05-10 20:24 UTC, martinvenus commented on AcceptanceTester.php
> +        $this->see($text);
Místo wait a see bych použil waitForText

Obecně není dobré wait používat. To že u tebe stačí počkat 5 sekund neznamená, že na jiném systému nebo počítači to bude stačit také. Pak ti budou náhodně padat testy, protože se nepočkalo dost dlouho. To se nám dělo a pak jsme se všech waitů zbavovali.

2018-05-10 20:24 UTC, martinvenus commented on AcceptanceTester.php
> +        public function verifySearchJizdniRad($tab,$odkud,$kam,$textToVerify){  //jízdní řád
Názvy proměnných by měly být vždy anglicky.

2018-05-10 20:24 UTC, martinvenus commented on AcceptanceTester.php
> +        $this->click('span.expander__button-in'); //Zobrazit přihlášení do emailu
Komentáře bych také psal anglicky. Obecně by veškerý zdrojový kód měl být anglicky.

2018-06-30 18:21 UTC, MichaelaRadimska commented on AcceptanceTester.php
> +        $this->see($text);
OK, zde ale tím textem testuji, jestli mne odkaz dostane na správnou stránku. Pokud se neobjeví, jsem jinde. Pokud se objeví, jsem možná správně, není to dokonalé.
Tzn. waitForText($text, 30) - časově omezit? Jinak to při chybě bude čekat do nekonečna? Zkoušela jsem seeInCurrentUrl, ale nefungovalo (neviděl daný text, ani když tam byl).

2018-06-30 18:23 UTC, MichaelaRadimska commented on AcceptanceTester.php
> +        public function verifySearchJizdniRad($tab,$odkud,$kam,$textToVerify){  //jízdní řád
OK, obecně chápu. Zde české názvy kopírují text na stránce - našeptávají, co do proměnné vložit. Přesto anglicky?

2018-06-30 18:29 UTC, MichaelaRadimska commented on AcceptanceTester.php
> +        $this->click('span.expander__button-in'); //Zobrazit přihlášení do emailu
dtto, zde komentář kopíruje text na stránce, přidala jsem ho pro snazší orientaci. Případně tedy komentář doplnit ve stylu "Text-Button: 'zobrazovany_text'"?

2018-07-02 15:19 UTC, MichaelaRadimska commented on AcceptanceTester.php
> +    public function verifyLink($link,$text){
Pochopila jsem správně, že striktní typování se v PHP týká jen parametru a návratového typu funkce? Tj. ne jako v C#/Javě, kde jsou striktně typovány všechny proměnné?

2019-01-25 16:47 UTC, closed without merging